# Generated by Django 3.1.3 on 2021-03-23 06:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, upload_to='package_images')),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='packages', to='python_packages.Category')),
            ],
        ),
    ]
