# Generated by Django 3.1.3 on 2021-03-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
