# Generated by Django 3.1.2 on 2021-05-02 01:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('python_packages', '0004_auto_20210323_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='meta_description',
            field=models.TextField(blank=True, max_length=170),
        ),
        migrations.AddField(
            model_name='package',
            name='pip_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='package',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
