# Generated by Django 3.1.2 on 2021-05-02 10:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_packages', '0005_auto_20210502_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='meta_data',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
