# Generated by Django 3.1.2 on 2021-09-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_packages', '0007_auto_20210512_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meta_data',
        ),
        migrations.RemoveField(
            model_name='package',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='pip_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='package',
            name='title',
        ),
    ]
