# Generated by Django 3.1.2 on 2021-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_packages', '0008_auto_20210925_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='affiliate_course',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='package',
            name='documentation',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
