# Generated by Django 3.1.3 on 2020-12-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_category_meta_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='book',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
