# Generated by Django 3.1.3 on 2020-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201211_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='size',
            field=models.FloatField(),
        ),
    ]
