# Generated by Django 3.1.3 on 2020-12-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201212_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.TextField(max_length=500),
        ),
    ]
