# Generated by Django 3.1.3 on 2020-12-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_link',
            field=models.URLField(max_length=500),
        ),
    ]
