# Generated by Django 3.1.3 on 2021-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210103_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='affiliate_link',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
