# Generated by Django 3.1 on 2020-10-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSubscriptions',
            new_name='EmailSubscription',
        ),
    ]
