# Generated by Django 3.1 on 2020-10-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
