# Generated by Django 3.1 on 2020-10-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201014_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='none', max_length=254),
            preserve_default=False,
        ),
    ]
