# Generated by Django 3.1.2 on 2020-10-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201016_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
