# Generated by Django 3.1 on 2020-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201023_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
