# Generated by Django 3.1 on 2020-11-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mostly_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
