# Generated by Django 2.1.3 on 2020-11-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201121_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_representation',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
