# Generated by Django 2.1.3 on 2020-11-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category_title_representation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(default='Python Tutorials', max_length=155),
            preserve_default=False,
        ),
    ]
