# Generated by Django 3.1.3 on 2020-12-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='', max_length=157),
            preserve_default=False,
        ),
    ]
