# Generated by Django 3.1.3 on 2021-03-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210105_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='important',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mostly_viewed',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
