# Generated by Django 3.1.3 on 2021-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210301_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, max_length=162),
        ),
    ]
