# Generated by Django 3.1.2 on 2021-09-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
