# Generated by Django 3.1.2 on 2021-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_post_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=170),
        ),
    ]
