# Generated by Django 3.1 on 2020-11-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='featured',
        ),
    ]
