# Generated by Django 3.1 on 2020-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0002_remove_package_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
