# Generated by Django 3.1 on 2020-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0003_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='project_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
