# Generated by Django 3.1 on 2020-11-11 13:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0005_auto_20201111_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
