# Generated by Django 3.1 on 2020-11-11 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0006_legaldoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDoc',
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
