# Generated by Django 3.1 on 2020-11-11 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0007_auto_20201111_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
