# Generated by Django 3.1 on 2020-11-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0008_auto_20201111_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
