# Generated by Django 2.1.3 on 2020-11-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_finder', '0009_auto_20201111_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
